"""
Data Generation Utilities
=========================
Utility functions for generating synthetic datasets used
throughout the neural network learning journey.

Functions:
    generate_spiral_data: Creates interlocking spiral arms for classification
"""

import numpy as np


def generate_spiral_data(n_samples_per_class=100, n_classes=3):
    """Generate a 2D spiral dataset for classification.

    Creates 'n_classes' interlocking spiral arms in 2D space.
    This dataset is non-linearly separable, making it a good
    challenge problem for neural networks.

    The spiral is generated by:
        1. Creating evenly-spaced radii from 0 to 1
        2. Creating angles that increase linearly with radius
        3. Adding noise to make the classification harder
        4. Offsetting angles by class_number * 4/N radians per class

    Args:
        n_samples_per_class: Number of points per spiral arm (default: 100)
        n_classes: Number of spiral arms / classes (default: 3)

    Returns:
        tuple:
            X (numpy.ndarray): Feature matrix of shape
                (n_samples_per_class * n_classes, 2).
                Column 0 = x-coordinate, Column 1 = y-coordinate.
            y (numpy.ndarray): Class labels of shape
                (n_samples_per_class * n_classes,), dtype uint8.
                Values range from 0 to n_classes - 1.
    """
    total_samples = n_samples_per_class * n_classes
    X = np.zeros((total_samples, 2))
    y = np.zeros(total_samples, dtype='uint8')

    for class_number in range(n_classes):
        # Slice indices for this class's samples
        start_idx = n_samples_per_class * class_number
        end_idx = n_samples_per_class * (class_number + 1)
        ix = range(start_idx, end_idx)

        # Radius: linearly spaced from 0 to 1
        r = np.linspace(0.0, 1, n_samples_per_class)

        # Angle: linear progression with noise for each class
        # Each class occupies a different angular segment
        t = np.linspace(
            class_number * 4,
            (class_number + 1) * 4,
            n_samples_per_class
        ) + np.random.randn(n_samples_per_class) * 0.2

        # Convert polar to cartesian coordinates
        # Using sin and cos creates the spiral pattern
        X[ix] = np.c_[
            r * np.sin(t * 2.5),
            r * np.cos(t * 2.5)
        ]
        y[ix] = class_number

    return X, y


def generate_linearly_separable_data(n_samples=300, n_classes=3):
    """Generate linearly separable 2D blobs for comparison.

    Uses Gaussian clusters that can be separated by straight lines.
    This is useful for comparing with the non-linear spiral data.

    Args:
        n_samples: Total number of samples (default: 300)
        n_classes: Number of Gaussian blobs (default: 3)

    Returns:
        tuple:
            X (numpy.ndarray): Feature matrix, shape (n_samples, 2)
            y (numpy.ndarray): Class labels, shape (n_samples,)
    """
    np.random.seed(42)
    samples_per_class = n_samples // n_classes
    X = []
    y = []

    for class_id in range(n_classes):
        # Center each blob at a different location
        center = np.random.uniform(-3, 3, size=2)
        class_samples = np.random.randn(samples_per_class, 2) + center
        X.append(class_samples)
        y.append(np.full(samples_per_class, class_id))

    X = np.vstack(X)
    y = np.concatenate(y)

    return X, y


if __name__ == "__main__":
    # Quick test when run directly
    X, y = generate_spiral_data(10, 3)
    print(f"Spiral data shape: {X.shape}")
    print(f"Labels shape: {y.shape}")
    print(f"Class distribution: {np.bincount(y)}")
    print(f"First 5 samples:\n{X[:5]}")
